spring:
  application:
    name: tlias-web-managerment
  datasource:
    url: jdbc:mysql://59.110.90.98:3306/ssmy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 617620
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true
